### ISSUE TITLE
Hardcoded 8080 port cause problem when running in dev mode (defaults to 4000)

### ISSUE THREAD

**Issue by h3** [xphong/marvel-vue-demo#2]
https://github.com/xphong/marvel-vue-demo/blob/62a9fde3fbd4bf1c55e76f88998fb7c3a2bd924a/client/store/index.js#L19

Probably a good idea to make the hostname dynamic too...

**Comment by h3** [comment]
Then I get this console error:

![err](https://user-images.githubusercontent.com/102919/32822956-02f7541e-c9a9-11e7-9705-1da7240e4374.png)

**Comment by kossa** [comment]
It should point to marvel.com there is nothing under /api in local

**Comment by xphong** [comment]
@h3 This happens because for this demo API url is based on https://github.com/xphong/marvel-powerlevels-api which is hosted on localhost:8080. 

@kossa Correct, it can also be pointed to marvel.com. Ex: `http://gateway.marvel.com/v1/public/characters?limit=12&nameStartsWith=${character}&apikey=${key}`

**Comment by h3** [comment]
Sorry, I just followed the README instructions.

I've just noticed there is a section about it [in the blog post](https://codeburst.io/marvel-api-vuepack-vue-vuex-c84067a7f7fc).

Might be a good idea to include it in the README ;)

**Comment by xphong** [comment]
@h3 👍  thanks for the suggestion.

README is updated.

Will close this issue.
